ALTER TYPE "EventType" ADD VALUE 'PROCESS_CREATED';
ALTER TYPE "EventType" ADD VALUE 'PROCESS_STARTED';
ALTER TYPE "EventType" ADD VALUE 'PROCESS_PAUSED';
ALTER TYPE "EventType" ADD VALUE 'PROCESS_RESUMED';
ALTER TYPE "EventType" ADD VALUE 'PROCESS_COMPLETED';
ALTER TYPE "EventType" ADD VALUE 'PROCESS_CANCELLED';
